In [1]:
import numpy as np

In [3]:
li=np.array([[2,-2,1],[-1,2,-1],[2,-4,1]])


In [4]:
li

array([[ 2, -2,  1],
       [-1,  2, -1],
       [ 2, -4,  1]])

In [6]:
ninf=np.linalg.norm(li,ord=np.inf)

In [7]:
ninf

7.0

In [10]:
n2=np.linalg.norm(li)
n2

6.0

In [29]:
A=np.array([[[1,-3,4],[-2,10,-7],[0,1,0],[0,0,0]]])

In [26]:
A

array([[ 1, -3,  4],
       [-2, 10, -7],
       [ 0,  1,  0],
       [ 0,  0,  0]])

In [30]:
B=np.array([[5,0],[-2,11],[-3,12]])

In [31]:
B

array([[ 5,  0],
       [-2, 11],
       [-3, 12]])

In [32]:
op=np.dot(A,B)

In [33]:
op

array([[[-1, 15],
        [-9, 26],
        [-2, 11],
        [ 0,  0]]])